import React, { useState } from 'react';
import { Send, Sparkles, Bot } from 'lucide-react';
import { getCareerAdvice } from '../services/geminiService';

interface CareerAssistantProps {
  jobTitle: string;
}

const CareerAssistant: React.FC<CareerAssistantProps> = ({ jobTitle }) => {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleAsk = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    const aiResponse = await getCareerAdvice(jobTitle, query);
    setResponse(aiResponse);
    setLoading(false);
  };

  return (
    <div className="relative group mt-8">
      {/* Glowing Orb Background */}
      <div className="absolute -inset-1 bg-gradient-to-r from-iridescent-middle to-biolum-cyan rounded-3xl blur-2xl opacity-20 group-hover:opacity-40 transition-opacity duration-1000 animate-pulse"></div>
      
      <div className="relative glass-membrane rounded-3xl p-8 overflow-hidden">
        
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
             <div className="relative w-10 h-10 flex items-center justify-center">
               <div className="absolute inset-0 bg-biolum-purple/20 rounded-full animate-ping"></div>
               <div className="relative bg-gradient-to-tr from-biolum-purple to-iridescent-middle w-10 h-10 rounded-full flex items-center justify-center text-white shadow-lg">
                 <Sparkles className="w-5 h-5" />
               </div>
             </div>
             <div>
               <h4 className="font-serif-fluid font-bold text-xl text-pearl-900 leading-none">Synapse AI</h4>
               <span className="text-xs font-mono text-gray-500 uppercase tracking-widest">Career Guide v2.0</span>
             </div>
          </div>
          <div className="px-3 py-1 rounded-full bg-pearl-100/50 border border-white/40 text-xs font-mono text-biolum-purple">
            ONLINE
          </div>
        </div>

        {/* AI Response Area */}
        {response && (
          <div className="mb-6 animate-scale-in origin-top">
            <div className="bg-gradient-to-br from-white/80 to-pearl-50/50 p-6 rounded-2xl border border-white shadow-sm relative">
               <div className="absolute -left-2 top-6 w-4 h-4 bg-white rotate-45 border-l border-b border-white"></div>
               <p className="text-sm md:text-base text-gray-700 leading-relaxed font-sans">
                 {response}
               </p>
               <div className="mt-3 flex items-center gap-2 justify-end opacity-50">
                 <Bot className="w-3 h-3" />
                 <span className="text-[10px] uppercase tracking-widest">Generated by Gemini</span>
               </div>
            </div>
          </div>
        )}

        {/* Input Area */}
        <div className="relative">
          <form onSubmit={handleAsk}>
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={`Pergunte sobre a vaga de ${jobTitle}...`}
              className="w-full bg-pearl-100/40 border border-pearl-200/60 rounded-2xl py-4 pl-5 pr-14 text-gray-800 placeholder-gray-400 focus:outline-none focus:bg-white focus:ring-2 focus:ring-biolum-cyan/20 focus:border-biolum-cyan/50 transition-all font-sans"
            />
            <button
              type="submit"
              disabled={loading || !query.trim()}
              className="absolute right-2 top-1/2 -translate-y-1/2 p-2.5 bg-black text-white rounded-xl hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all hover:scale-105 active:scale-95 shadow-lg"
            >
              {loading ? (
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              ) : (
                <Send className="w-4 h-4" />
              )}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default CareerAssistant;